version: '2'

networks:
    proxy:
        external:
            name: common_proxy

services:
    __app_name___client:
        container_name: __app_name___client
        build: .
        command: yarn start
        working_dir: /code
        ports:
            - "4004:4004"
        volumes:
            - .:/code:cached
            - /code/node_modules
        networks:
            - proxy
        tty: true

