version: '2'

networks:
    proxy:
        external:
            name: common_proxy

services:
    kpkg_client:
        container_name: kpkg_client
        build:
            context: ./
        command: yarn start
        working_dir: /code
        ports:
            - "4004:4004"
        volumes:
            - .:/code:cached
            - /code/node_modules
        networks:
            - proxy

