# Generated by Django 2.0 on 2018-04-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=256, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=50)),
                ('single', models.BooleanField()),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['-id'],
                'permissions': (('view_category_list', 'Can view category list'), ('view_category_detail', 'Can view category detail')),
            },
        ),
    ]
