# Generated by Django 2.0.7 on 2018-07-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_category_width_ratio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'permissions': (('list_category', 'Can list category'), ('retrieve_category', 'Can retrieve category'))},
        ),
    ]
