# Generated by Django 2.0 on 2018-04-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_auto_20180407_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='uuid',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
