# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'ordering': ['-id'], 'permissions': (('view_list_administrator', 'Can view list administrators'), ('view_detail_administrator', 'Can view detail administrators'))},
        ),
    ]
