# Generated by Django 2.0 on 2017-12-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_auto_20170705_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='change_password_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='administrator',
            name='change_password_tmp',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='administrator',
            name='change_password_token',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='administrator',
            name='reset_password_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='administrator',
            name='reset_password_tmp',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='administrator',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
