# Generated by Django 2.0 on 2018-01-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_auto_20171229_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='reset_password_token',
            new_name='signup_token',
        ),
        migrations.RenameField(
            model_name='administrator',
            old_name='reset_password_created',
            new_name='signup_token_created',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='reset_password_tmp',
        ),
    ]
