# Generated by Django 2.0 on 2018-01-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_auto_20180116_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='change_password_created',
            new_name='reset_password_created',
        ),
        migrations.RenameField(
            model_name='administrator',
            old_name='change_password_tmp',
            new_name='reset_password_tmp',
        ),
        migrations.RenameField(
            model_name='administrator',
            old_name='change_password_token',
            new_name='reset_password_token',
        ),
    ]
