# Generated by Django 2.0 on 2018-03-31 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_auto_20180120_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'ordering': ['-id'], 'permissions': (('view_administrator_list', 'Can view administrator list'), ('view_administrator_detail', 'Can view administrator detail'), ('view_administrator_profile', 'Can view administrator profile'))},
        ),
    ]
