# Generated by Django 2.0 on 2018-05-13 07:30

from django.db import migrations, models
import apps.staff.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=56)),
                ('fullname', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to=apps.staff.models.image_destination)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'staffs',
                'ordering': ['-id'],
                'permissions': (('view_staff_list', 'Can view staff list'), ('view_staff_detail', 'Can view staff detail')),
            },
        ),
    ]
