# Generated by Django 2.0 on 2018-05-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('url', models.CharField(blank=True, max_length=256)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
            options={
                'db_table': 'ccalendars',
                'ordering': ['-start'],
                'permissions': (('view_ccalendar_list', 'Can view ccalendar list'), ('view_ccalendar_detail', 'Can view ccalendar detail')),
            },
        ),
    ]
