# Generated by Django 2.0 on 2018-04-01 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_auto_20180401_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='category/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
            options={
                'db_table': 'banners',
                'ordering': ['-id'],
                'permissions': (('view_banner_list', 'Can view banner list'), ('view_banner_detail', 'Can view banner detail')),
            },
        ),
    ]
