# Generated by Django 2.0.7 on 2018-08-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0007_bannertranslation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-id'], 'permissions': (('list_banner', 'Can list banner'), ('retrieve_banner', 'Can retrieve banner'), ('delete_list_banner', 'Can delete list banner'), ('change_translation_banner', 'Can change translation banner'))},
        ),
        migrations.AlterModelOptions(
            name='bannertranslation',
            options={'default_permissions': (), 'ordering': ['-id']},
        ),
    ]
