# Generated by Django 2.0 on 2018-04-07 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_auto_20180407_0914'),
        ('article', '0002_article_relatedarticle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='relatedArticle',
            new_name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatedArticles', to='banner.Banner'),
        ),
    ]
