# Generated by Django 2.0 on 2018-04-14 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-order'], 'permissions': (('view_article_list', 'Can view article list'), ('view_article_detail', 'Can view article detail'))},
        ),
    ]
