# Generated by Django 2.0 on 2018-04-14 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20180414_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='banner',
        ),
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatedArticles', to='article.Article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='category.Category'),
        ),
    ]
