# Generated by Django 2.0 on 2018-04-21 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20180414_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_articles', to='article.Article'),
        ),
    ]
