# Generated by Django 2.0 on 2018-07-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_article_thumbnail_in_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='uid',
            new_name='slug',
        ),
    ]
