# Generated by Django 2.0.7 on 2018-08-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_articletranslation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-order'], 'permissions': (('list_article', 'Can list article'), ('retrieve_article', 'Can retrieve article'), ('delete_list_article', 'Can delete list article'))},
        ),
    ]
