# Generated by Django 2.0 on 2018-04-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='single',
            field=models.BooleanField(default=False),
        ),
    ]
