# Generated by Django 2.0 on 2018-05-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_image_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='width_ratio',
            field=models.IntegerField(default=100),
        ),
    ]
