# Generated by Django 2.0.7 on 2018-07-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_auto_20180728_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'permissions': (('list_category', 'Can list category'), ('retrieve_category', 'Can retrieve category'), ('delete_list_category', 'Can delete list category'))},
        ),
    ]
