# Generated by Django 2.0 on 2018-04-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180408_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='uuid',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
