# Generated by Django 2.0 on 2018-04-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20180421_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='use_slide',
            field=models.BooleanField(default=False),
        ),
    ]
