# Generated by Django 2.0 on 2018-05-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pin',
            field=models.BooleanField(default=False),
        ),
    ]
