# Generated by Django 2.0 on 2018-04-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attach', '0003_attach_richtext_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attach',
            name='filetype',
            field=models.CharField(default='image', max_length=32),
        ),
    ]
