# Generated by Django 2.0 on 2018-03-31 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20170705_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['-id'], 'permissions': (('view_config_list', 'Can view list configs'), ('view_config_detail', 'Can view detail config'))},
        ),
    ]
