# Generated by Django 2.0 on 2018-03-31 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20180331_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['-id'], 'permissions': (('view_config_list', 'Can view config list'), ('view_config_detail', 'Can view config detail'))},
        ),
    ]
