# Generated by Django 2.0.7 on 2018-07-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_auto_20180728_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['-id'], 'permissions': (('list_config', 'Can list config'), ('retrieve_config', 'Can retrieve config'))},
        ),
    ]
