# Generated by Django 2.0.7 on 2018-07-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_auto_20180728_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['-id'], 'permissions': (('list_config', 'Can list config'), ('retrieve_config', 'Can retrieve config'), ('delete_list_config', 'Can delete list config'))},
        ),
    ]
