# Generated by Django 2.0.7 on 2018-07-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_auto_20180512_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-id'], 'permissions': (('list_tag', 'Can list tag'), ('retrieve_tag', 'Can retrieve tag'), ('delete_list_tag', 'Can delete list tag'))},
        ),
    ]
