# Generated by Django 2.0 on 2018-05-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('uid', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['-id'],
                'permissions': (('view_tag_list', 'Can view tag list'), ('view_tag_detail', 'Can view tag detail')),
            },
        ),
    ]
