# Generated by Django 2.0 on 2018-04-10 00:51

import apps.attach.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_uuid', models.CharField(max_length=36)),
                ('parent_table', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=256)),
                ('attachment', models.FileField(upload_to=apps.attach.models.file_destination)),
            ],
            options={
                'db_table': 'attaches',
                'ordering': ['-id'],
                'permissions': (('view_attach_list', 'Can view attach list'), ('view_attach_detail', 'Can view attach detail')),
            },
        ),
    ]
