# Generated by Django 2.0 on 2018-04-11 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attach', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attach',
            name='parent_table',
        ),
    ]
